# Generated by Django 3.2.19 on 2023-06-17 16:01

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='food_images/'),
        ),
    ]
