# Generated by Django 3.2.19 on 2023-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_foodlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
